import { createStyles, keyframes } from "@mantine/core";
import download from "../../assets/download.png";
export const bigToSmall = keyframes({
  from: { transform: "scale(1.5)", margin: "50px" },
  to: { transform: "scale(1)", margin: "0px" },
});
export const useStyles = createStyles((theme, props) => ({
  home: {
    color: "white",
    minHeight: "400px",
    position: "relative",
    paddingTop: "150px !important",
    marginBottom: "20px",
    ":after": {
      content: '""',
      background:
        "linear-gradient(to right, rgb(4, 143, 200) , rgb(101, 230, 223))",
      // backgroundColor: "rgb(4, 143, 200)",
      position: "absolute",
      width: "100%",
      height: "78%",
      zIndex: -1,
      top: 0,
      left: 0,
      [`@media (max-width: 1200px)`]: {
        height: "100%",
      },
    },
  },
  homeCard: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: "5px",
    backgroundColor: theme.colors.green,
    width: "150px",
    height: "150px",
    aspectRatio: "1/1",
    borderRadius: "50%",
    border: "5px solid white",
    padding: "2px",
    [`@media (max-width: 820px)`]: {
      width: "100px",
      height: "100px",
    },
  },
  about: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    gap: "25px",
    padding: "0px",
    marginBottom: "30px",
  },
  projects: {
    paddingBlock: "100px",
    backgroundColor: "rgb(240, 240, 240)",
    color: "black",
  },
  projectsDiv: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    gap: "5px",
    padding: "15px",
    paddingRight: "50px",
    "& > img": {
      padding: "20px",
      // width: "40px",
      // height: "40px",
      aspectRatio: "1/1",
      borderRadius: "35% 35% 0 35%",
      backgroundColor: theme.colors.green,
    },
  },
  services: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: "25px",
    padding: "0px",
    marginBottom: "50px",
  },
  servicesSub: {
    position: "relative",
    width: "90%",
    height: "1000px",
    [`@media (max-width: 1020px)`]: {
      height: "100%",
    },
    // backgroundColor: "red",
  },
  cat: {
    position: "absolute",
    width: "80%",
    "& > img": {
      width: "90px",
      height: "90px !important",
      padding: "10px",
      borderWidth: "2px",
      borderStyle: "solid",
      borderColor: theme.colors.green,
      borderRadius: "30% 30% 0% 30%",
    },
    [`@media (max-width: 992px)`]: {
      position: "static",
      width: "100%",
      padding: "10px",
      "& > img": {
        width: "50px",
        height: "50px !important",
        padding: "10px",
        backgroundColor: theme.colors.green,
        // borderRadius: "30% 30% 0% 30%",
      },
    },
    "&: first-of-type": {
      top: "2%",
      left: "-20%",
    },
    "&: nth-of-type(2)": {
      top: "20%",
      left: "0%",
    },
    "&: nth-of-type(3)": {
      top: "38%",
      left: "10%",
    },
    "&: nth-of-type(4)": {
      top: "56%",
      left: "10%",
    },
    "&: nth-of-type(5)": {
      top: "74%",
      left: "0%",
    },
    "&: nth-of-type(6)": {
      top: "92%",
      left: "-20%",
    },
  },
  download: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: "30px",
    minHeight: "550px",
    backgroundImage: `url(${download}) `,
    backgroundPosition: "50%",
    backgroundSize: "cover",
    position: "relative",
    zIndex: -1,
    color: "white",
    ":after": {
      content: '""',
      width: "100%",
      height: "100%",
      top: 0,
      zIndex: -1,
      position: "absolute",
      backgroundColor: "rgb(45, 62, 80, 0.85)",
    },
  },
  storeButton: {
    border: "1px solid white",
    padding: "10px 20px",
  },
  review: {
    backgroundColor: "rgb(240, 240, 240)",
    padding: "10px 40px",
    borderRadius: "10px",
  },
  appSS: {
    height: "500px",
    width: "50%",
    marginInline: "auto",
    marginBlock: "100px",
    [`@media (max-width: 1200px)`]: {
      width: "100%",
    },
  },
  goToTop: {
    position: "fixed",
    bottom: 40,
    right: 20,
    backgroundColor: theme.colors.green,
    color: "white",
    borderRadius: "50%",
    padding: "10px",
    cursor: "pointer",
    transition: "0.5s ease all",
    zIndex: 999,
    ":hover": {
      opacity: 0.9,
    },
  },
}));
